In [2]:
import pandas as pd
import numpy as np
import time

In [3]:
board_size = 6
win_length = 5
player = 1

In [4]:
directions = [(-1, -1),
            (-1, 0),
            (-1, 1),
            (0, -1),
            (0, 1),
            (1, -1),
            (1, 0),
            (1, 1)
            ]

In [37]:
def check_alignement_capture(board, row, col, player):
    for dr, dc in directions:
        r, c = row + dr, col + dc
        if 0 <= r < len(board) and 0 <= c < len(board):
            if board[r][c] == -player:  # Found an opponent piece
                # search in the same direction for another opponent piece
                r2, c2 = r + dr, c + dc
                if 0 <= r2 < len(board) and 0 <= c2 < len(board):
                    if board[r2][c2] == -player:
                        # check if the next cell in the same direction is player's piece
                        r3, c3 = r2 + dr, c2 + dc
                        if 0 <= r3 < len(board) and 0 <= c3 < len(board):
                            if board[r3][c3] == player:
                                return True
    return False

In [35]:
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[1][0] = 1
tab[2][0] = -1
tab[3][0] = -1
tab[4][0] = 0
# tab[1][0] = -1
# tab[1][1] = 0
# tab[1][2] = 1
# tab[1][3] = 1
# tab[2][3] = 1
# tab[1][0] = 1
# tab[2][0] = 1
# tab[3][0] = 1

print(tab)

[[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [-1  0  0  0  0  0]
 [-1  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [ ]:
score = {"1": 2, "-1": 1}
row = 4
col = 0
print(type(score["1"]))

KeyError: 1

In [ ]:
scores = [0,
          10,
          100,
          1000,
          10**(win_len)
            ]

print(tab)
res = 0
if check_alignement_capture(tab, row, col, player):
    res += score[str(player)]
print(res)

[[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [-1  0  0  0  0  0]
 [-1  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
2


In [47]:
win_len = 5
reward_closed = [0] * (win_len + 1)
reward_open1 = [0] + [0] + [10**i for i in range(-2, win_len, 2)]
reward_open2 = [0] + [0] + [10**i for i in range(-1, win_len + 1, 2)]
reward_closed[win_len] = 10**(win_len)
reward_open1[win_len] = 10**(win_len)
reward = [reward_closed, reward_open1, reward_open2]
print(reward)

[[0, 0, 0, 0, 0, 100000], [0, 0, 0.01, 1, 100, 100000], [0, 0, 0.1, 10, 1000, 100000]]


In [68]:
reward_capture = [100 + 10**(i+1) for i in range(5)]
reward_capture[4] = 10**(win_len)
print(reward_capture)

[110, 200, 1100, 10100, 100000]


In [ ]:
res = 0
if check_alignement_capture(tab, row, col, player):
    res += reward_capture[score[str(player)]]
print(res)

200


In [9]:
board_size = 6
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[1][1] = 1
tab[2][1] = 1
tab[3][2] = 1
tab[3][3] = 1
tab[5][4] = -1
tab[5][3] = -1
tab[4][5] = -1
# tab[1][1] = 0
# tab[1][2] = 1
# tab[1][3] = 1
# tab[2][3] = 1
# tab[1][0] = 1
# tab[2][0] = 1
# tab[3][0] = 1

print(tab)

[[ 0  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  0  0 -1]
 [ 0  0  0 -1 -1  0]]


In [20]:
%cd ..
from src.valid_move import check_threes
%load_ext autoreload
%autoreload 2

check_threes(tab, 1, 3, 1)

/
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
i,j = 1 1 => 1
i,j = 1 2 => 1
i,j = 1 3 => 0
i,j = 1 4 => 0
i,j = 2 3 => 1
i,j = 2 4 => 0
i,j = 2 5 => 0
i,j = 3 1 => 1
i,j = 3 2 => 0
i,j = 3 3 => 1
i,j = 3 4 => 0
Check double threes 1 0
i,j = 1 1 => 1
i,j = 1 2 => 0
i,j = 1 3 => 1
i,j = 1 4 => 0
i,j = 2 1 => 1
i,j = 2 2 => 0
i,j = 2 3 => 0
i,j = 3 2 => 1
i,j = 3 3 => 1
i,j = 3 4 => 0
i,j = 3 5 => 0
Check double threes 2 0
Check double threes 3 0
Check double threes 4 0


False

In [51]:
board_size = 6
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[4][1] = 1
tab[1][2] = 1
tab[3][2] = 1
tab[3][4] = 1
tab[2][3] = 5
tab[1][1] = 6
# tab[1][2] = 1
# tab[1][3] = 1
# tab[2][3] = 1
# tab[1][0] = 1
# tab[2][0] = 1
# tab[3][0] = 1

print(tab)

[[0 0 0 0 0 0]
 [0 6 1 0 0 0]
 [0 0 0 5 0 0]
 [0 0 1 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]


In [52]:
tb = np.rot90(tab, k = 1)
print(tb)
tb[2][2] = 7
print(tb)

[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 5 0 0 0]
 [0 1 0 1 0 0]
 [0 6 0 0 1 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 7 0 0 0]
 [0 1 0 1 0 0]
 [0 6 0 0 1 0]
 [0 0 0 0 0 0]]


In [54]:
%cd ..
from src.valid_move import check_threes
%load_ext autoreload
%autoreload 2

check_threes(tab, 1, 2, 3)

/
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Check double threes 1 0
Check double threes 2 0
i,i-j = 1 2 => 1
i,i-j = 2 3 => 1
i,i-j = 3 4 => 1
i,i-j = 3 2 => 1
i,i-j = 4 3 => 0
i,i-j = 5 4 => 0
i,i-j = 4 1 => 1
i,i-j = 5 2 => 0
Check double threes 3 1
i,i-j = 1 3 => 1
i,i-j = 2 4 => 0
i,i-j = 3 5 => 0
i,i-j = 2 2 => 1
i,i-j = 3 3 => 1
i,i-j = 4 4 => 1
i,i-j = 3 1 => 1
i,i-j = 4 2 => 0
i,i-j = 5 3 => 0
Check double threes 4 2


True