In [2]:
import pandas as pd
import numpy as np
import time

In [ ]:
board_size = 19
win_len = 5
tab_init = pd.DataFrame(0, index=range(19), columns=range(19))

In [37]:
tab_init[2][2]

np.float64(nan)

In [90]:
def check_direction(board_size, win_len, tab, player, row, col, delta_row, delta_col):
    count = 0
    for k in range(win_len):
        r = row + k * delta_row
        c = col + k * delta_col
        if 0 <= r < board_size and 0 <= c < board_size and tab[r][c] == tab[row][col] and tab[r][c] == player:
            count += 1
        else:
            break
    return count == win_len

In [91]:
def basic_heuristic(board_size, win_len, tab, player):
    for i in range(board_size):
        for j in range(board_size):
            if tab[i][j] is not np.nan:
                if check_direction(board_size, win_len, tab, player, i, j, 1, 0):
                    return 1000
    return 0            

In [92]:
result = basic_heuristic(19, 5, tab_init, 1)
print(result)

0


In [94]:
def heuristic(board_size, win_len, tab, player):
    start = time.perf_counter()
    for i in range(board_size):
        for j in range(board_size):
            if tab[i][j] != 0:
                if check_direction(board_size, win_len, tab, player, i, j, 1, 0) or \
                    check_direction(board_size, win_len, tab, player, i, j, 0, 1) or \
                    check_direction(board_size, win_len, tab, player, i, j, 1, 1) or \
                    check_direction(board_size, win_len, tab, player, i, j, 1, -1):
                    return 1000
    result = 0
    if win_len > 1:
        for i in range(board_size):
            for j in range(board_size):
                if tab[i][j] != 0:
                    if check_direction(board_size, win_len - 1, tab, player, i, j, 1, 0) or \
                        check_direction(board_size, win_len - 1, tab, player, i, j, 0, 1) or \
                        check_direction(board_size, win_len - 1, tab, player, i, j, 1, 1) or \
                        check_direction(board_size, win_len - 1, tab, player, i, j, 1, -1):
                        result += 20
    if win_len > 2:
        for i in range(board_size):
            for j in range(board_size):
                if tab[i][j] != 0:
                    if check_direction(board_size, win_len - 2, tab, player, i, j, 1, 0) or \
                        check_direction(board_size, win_len - 2, tab, player, i, j, 0, 1) or \
                        check_direction(board_size, win_len - 2, tab, player, i, j, 1, 1) or \
                        check_direction(board_size, win_len - 2, tab, player, i, j, 1, -1):
                        result += 10
    if win_len > 3:
        for i in range(board_size):
            for j in range(board_size):
                if tab[i][j] != 0:
                    if check_direction(board_size, win_len - 3, tab, player, i, j, 1, 0) or \
                        check_direction(board_size, win_len - 3, tab, player, i, j, 0, 1) or \
                        check_direction(board_size, win_len - 3, tab, player, i, j, 1, 1) or \
                        check_direction(board_size, win_len - 3, tab, player, i, j, 1, -1):
                        result += 1
    end = time.perf_counter()
    print(f"Heuristic in {(end - start)*1000:0.4f} milliseconds")
    return result  

In [95]:
result = heuristic(19, 5, tab_init, 1)
print(result)

Heuristic in 2.6659 milliseconds
0


In [96]:
tab = pd.DataFrame(0, index=range(5), columns=range(5))
#tab = [[np.nan for _ in range(19)] for _ in range(19)]
tab.loc[0, 0] = 1
tab.loc[0, 1] = 1
tab.loc[0, 2] = 1
tab.loc[0, 3] = 1
tab.loc[0, 4] = 1
tab.loc[1, 0] = 0
tab.loc[1, 1] = 0
tab.loc[1, 2] = 0
tab.loc[1, 3] = 0
tab.loc[1, 4] = 0
print(tab)

   0  1  2  3  4
0  1  1  1  1  1
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0


In [97]:
result = heuristic(19, 5, tab, 1)
print(result)

1000


In [ ]:
tab = pd.DataFrame(0, index=range(5), columns=range(5))
#tab = [[np.nan for _ in range(19)] for _ in range(19)]
#tab.loc[0, 1] = 1
#tab.loc[0, 2] = 1
#tab.loc[0, 3] = 1
#tab.loc[0, 4] = -1
#tab.loc[1, 0] = -1
#tab.loc[1, 1] = -1
#tab.loc[1, 2] = -1
#tab.loc[1, 3] = -1
#tab.loc[1, 4] = -1
tab.loc[1, 0] = 1
tab.loc[2, 0] = 1
tab.loc[3, 0] = 1
print(tab)

   0  1  2  3  4
0  0  0  0  0  0
1  1  0  0  0  0
2  1  0  0  0  0
3  1  0  0  0  0
4  0  0  0  0  0


In [ ]:
reward = [[0, 0, 0, 0, 0, 100000], #closed
          [0, 0, 0.1, 1, 100, 100000], #open 1
          [0, 0, 0.5, 10, 1000, 100000] #open 2
          ]
player = 1
board_size = 5
win_len = 5
i = 0
j = 0
result = 0
while j <= board_size - 1:
    if tab[j][i] == player:
        open = 0
        if j - 1 >= 0:
            if tab[j - 1][i] == 0:
                open = 1
        k = 0
        while k <= win_len and j <= board_size - 1 and tab[j][i] == player:
            k += 1
            j += 1
        if j <= board_size:
            if tab[j][i] == 0:
                open += 1
        #if k == win_len
        #    return 100000
        result += reward[open][k]
        if tab[j][i] == - player:
            open = 0
            if j - 1 >= 0:
                if tab[j - 1][i] == 0:
                    open = 1
            k = 0
            while k <= win_len and j <= board_size - 1 and tab[j][i] == - player:
                k += 1
                j += 1
            if j <= board_size:
                if tab[j][i] == 0:
                    open += 1
            #if k == win_len
            #    return -100000
        result -= reward[open][k]
    else:
        j += 1

In [82]:
def row_lines(board_size, win_len, tab, player):
    i = 0
    result = 0
    while i <= board_size - 1:
        j = 0
        while j <= board_size - 1:
            if tab[j][i] == player:
                open = 0
                if j - 1 >= 0:
                    if tab[j - 1][i] == 0:
                        open = 1
                k = 0
                while k <= win_len and j <= board_size - 1 and tab[j][i] == player:
                    k += 1
                    j += 1
                if j <= board_size - 1:
                    if tab[j][i] == 0:
                        open += 1
                result += reward[open][k]
            elif tab[j][i] == - player:
                open = 0
                if j - 1 >= 0:
                    if tab[j - 1][i] == 0:
                        open = 1
                k = 0
                while k <= win_len and j <= board_size - 1 and tab[j][i] == - player:
                    k += 1
                    j += 1
                if j <= board_size - 1:
                    if tab[j][i] == 0:
                        open += 1
                result -= reward[open][k]
            else:
                j += 1
        i += 1
    return result

In [87]:
player = 1
res = row_lines(board_size, win_len, tab, player)
res += row_lines(board_size, win_len, tab.transpose(), player)
print(res)

10


In [ ]:
player = 1
board_size = 5
win_len = 5
i = 0
j = 0
result = 0


100000

In [91]:
import numpy as np
import pandas as pd
from scipy.ndimage import rotate

# Exemple de tableau NumPy
#array = np.random.rand(10, 10)  # Remplacez cela par votre tableau ou DataFrame

array = pd.DataFrame(0, index=range(5), columns=range(5))
print(array)

# Rotation de 45 degrés
rotated_array = rotate(array, 45, reshape=True)

print(rotated_array)

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
