In [4]:
import pandas as pd
import numpy as np
import time

In [ ]:
board_size = 19
win_len = 5
tab_init = pd.DataFrame(0, index=range(19), columns=range(19))

In [37]:
tab_init[2][2]

np.float64(nan)

In [90]:
def check_direction(board_size, win_len, tab, player, row, col, delta_row, delta_col):
    count = 0
    for k in range(win_len):
        r = row + k * delta_row
        c = col + k * delta_col
        if 0 <= r < board_size and 0 <= c < board_size and tab[r][c] == tab[row][col] and tab[r][c] == player:
            count += 1
        else:
            break
    return count == win_len

In [91]:
def basic_heuristic(board_size, win_len, tab, player):
    for i in range(board_size):
        for j in range(board_size):
            if tab[i][j] is not np.nan:
                if check_direction(board_size, win_len, tab, player, i, j, 1, 0):
                    return 1000
    return 0            

In [92]:
result = basic_heuristic(19, 5, tab_init, 1)
print(result)

0


In [94]:
def heuristic(board_size, win_len, tab, player):
    start = time.perf_counter()
    for i in range(board_size):
        for j in range(board_size):
            if tab[i][j] != 0:
                if check_direction(board_size, win_len, tab, player, i, j, 1, 0) or \
                    check_direction(board_size, win_len, tab, player, i, j, 0, 1) or \
                    check_direction(board_size, win_len, tab, player, i, j, 1, 1) or \
                    check_direction(board_size, win_len, tab, player, i, j, 1, -1):
                    return 1000
    result = 0
    if win_len > 1:
        for i in range(board_size):
            for j in range(board_size):
                if tab[i][j] != 0:
                    if check_direction(board_size, win_len - 1, tab, player, i, j, 1, 0) or \
                        check_direction(board_size, win_len - 1, tab, player, i, j, 0, 1) or \
                        check_direction(board_size, win_len - 1, tab, player, i, j, 1, 1) or \
                        check_direction(board_size, win_len - 1, tab, player, i, j, 1, -1):
                        result += 20
    if win_len > 2:
        for i in range(board_size):
            for j in range(board_size):
                if tab[i][j] != 0:
                    if check_direction(board_size, win_len - 2, tab, player, i, j, 1, 0) or \
                        check_direction(board_size, win_len - 2, tab, player, i, j, 0, 1) or \
                        check_direction(board_size, win_len - 2, tab, player, i, j, 1, 1) or \
                        check_direction(board_size, win_len - 2, tab, player, i, j, 1, -1):
                        result += 10
    if win_len > 3:
        for i in range(board_size):
            for j in range(board_size):
                if tab[i][j] != 0:
                    if check_direction(board_size, win_len - 3, tab, player, i, j, 1, 0) or \
                        check_direction(board_size, win_len - 3, tab, player, i, j, 0, 1) or \
                        check_direction(board_size, win_len - 3, tab, player, i, j, 1, 1) or \
                        check_direction(board_size, win_len - 3, tab, player, i, j, 1, -1):
                        result += 1
    end = time.perf_counter()
    print(f"Heuristic in {(end - start)*1000:0.4f} milliseconds")
    return result  

In [95]:
result = heuristic(19, 5, tab_init, 1)
print(result)

Heuristic in 2.6659 milliseconds
0


In [ ]:
tab = pd.DataFrame(0, index=range(5), columns=range(5))
#tab = [[np.nan for _ in range(19)] for _ in range(19)]
tabtab[0, 0] = 1
tab.loc[0, 1] = 1
tab.loc[0, 2] = 1
tab.loc[0, 3] = 1
tab.loc[0, 4] = 1
tab.loc[1, 0] = 0
tab.loc[1, 1] = 0
tab.loc[1, 2] = 0
tab.loc[1, 3] = 0
tab.loc[1, 4] = 0
print(tab)

   0  1  2  3  4
0  1  1  1  1  1
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0


In [97]:
result = heuristic(19, 5, tab, 1)
print(result)

1000


In [33]:
tab = pd.DataFrame(0, index=range(5), columns=range(5))
#tab = [[np.nan for _ in range(19)] for _ in range(19)]
tab.loc[0, 0] = 7
#tab.loc[0, 1] = 1
tab.loc[0, 2] = 1
tab.loc[4, 1] = 1
#tab.loc[0, 3] = 1
tab.loc[0, 4] = -1
tab.loc[1, 0] = -1
tab.loc[1, 1] = -1
tab.loc[1, 2] = 1
tab.loc[2, 3] = 1
#tab.loc[1, 4] = -1
tab.loc[1, 0] = 1
tab.loc[2, 0] = 1
tab.loc[3, 0] = 1
print(tab)

   0  1  2  3  4
0  7  0  1  0 -1
1  1 -1  1  0  0
2  1  0  0  1  0
3  1  0  0  0  0
4  0  1  0  0  0


In [ ]:
reward = [[0, 0, 0, 0, 0, 100000], #closed
          [0, 0, 0.1, 1, 100, 100000], #open 1
          [0, 0, 0.5, 10, 1000, 100000] #open 2
          ]
player = 1
board_size = 5
win_len = 5
i = 0
j = 0
result = 0
while j <= board_size - 1:
    if tab[j][i] == player:
        open = 0
        if j - 1 >= 0:
            if tab[j - 1][i] == 0:
                open = 1
        k = 0
        while k <= win_len and j <= board_size - 1 and tab[j][i] == player:
            k += 1
            j += 1
        if j <= board_size:
            if tab[j][i] == 0:
                open += 1
        #if k == win_len
        #    return 100000
        result += reward[open][k]
        if tab[j][i] == - player:
            open = 0
            if j - 1 >= 0:
                if tab[j - 1][i] == 0:
                    open = 1
            k = 0
            while k <= win_len and j <= board_size - 1 and tab[j][i] == - player:
                k += 1
                j += 1
            if j <= board_size:
                if tab[j][i] == 0:
                    open += 1
            #if k == win_len
            #    return -100000
        result -= reward[open][k]
    else:
        j += 1

In [ ]:
def row_lines(board_size, win_len, tab, player):
    i = 0
    result = 0
    while i <= board_size - 1:
        j = 0
        while j <= board_size - 1:
            if tab[j][i] == player:
                open = 0
                if j - 1 >= 0:
                    if tab[j - 1][i] == 0:
                        open = 1
                k = 0
                while k <= win_len and j < board_size and tab[j][i] == player:
                    k += 1
                    j += 1
                if j < board_size:
                    if tab[j][i] == 0:
                        open += 1
                result += reward[open][k]
            elif tab[j][i] == -player:
                open = 0
                if j - 1 >= 0:
                    if tab[j - 1][i] == 0:
                        open = 1
                k = 0
                while k <= win_len and j < board_size and tab[j][i] == -player:
                    k += 1
                    j += 1
                if j < board_size:
                    if tab[j][i] == 0:
                        open += 1
                result -= reward[open][k]
            else:
                j += 1
        i += 1
    return result

In [87]:
player = 1
res = row_lines(board_size, win_len, tab, player)
res += row_lines(board_size, win_len, tab.transpose(), player)
print(res)

10


In [49]:
data = np.arange(1, 26).reshape(5, 5)
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'], columns=['A', 'B', 'C', 'D', 'E'])

print("DataFrame original:")
print(df)

# Fonction pour parcourir et afficher les diagonales parallèles à l'anti-diagonale
def parcourir_diagonales_anti_principales(df):
    n = df.shape[0]
    for d in range(2 * n - 1):
        diagonale = []
        for i in range(max(0, d - n + 1), min(n, d + 1)):
            j = n - 1 - (d - i)
            diagonale.append(df.iloc[i, j])
        print(f"Anti-diagonale {d}: {diagonale}")

#print("\nDiagonales parallèles à l'anti-diagonale:")
#parcourir_diagonales_anti_principales(df)

# Fonction pour parcourir et afficher les diagonales parallèles à la diagonale principale
def parcourir_diagonales_principales(df):
    n = df.shape[0]
    for d in range(-n + 1, n):
        diagonale = []
        for i in range(max(0, d), min(n, d + n)):
            diagonale.append(df.iloc[i, i - d])
        print(f"Diagonale {d}: {diagonale}")

print("\nDiagonales parallèles à la diagonale principale:")
parcourir_diagonales_principales(df)

DataFrame original:
    A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20
e  21  22  23  24  25

Diagonales parallèles à la diagonale principale:
Diagonale -4: [np.int64(5)]
Diagonale -3: [np.int64(4), np.int64(10)]
Diagonale -2: [np.int64(3), np.int64(9), np.int64(15)]
Diagonale -1: [np.int64(2), np.int64(8), np.int64(14), np.int64(20)]
Diagonale 0: [np.int64(1), np.int64(7), np.int64(13), np.int64(19), np.int64(25)]
Diagonale 1: [np.int64(6), np.int64(12), np.int64(18), np.int64(24)]
Diagonale 2: [np.int64(11), np.int64(17), np.int64(23)]
Diagonale 3: [np.int64(16), np.int64(22)]
Diagonale 4: [np.int64(21)]


In [ ]:
player = 1
board_size = 5
win_len = 5
i = 0
j =  1 - board_size
result = 0

print(tab)

while j < board_size:
    print('\nj', j)
    i = max(0, j)
    while i < min(board_size, j + board_size):
        print(f'tab[{i}][{i - j}]   ', tab[i][i - j])
        if tab[i][i - j] == player:
                open = 0
                if i - 1 >= 0 and i - 1 - j >= 0:
                    print(f"tab[{i - 1}][{i - 1 - j}] {tab[i - 1][i - 1 - j]}")
                    if tab[i - 1][i - 1 - j] == 0:
                        open = 1
                print(f"open {open}")
                k = 0
                while k <= win_len and i < min(board_size, j + board_size) and tab[i][i - j] == player:
                    print(f'tab[{i}][{i - j}]   ', tab[i][i - j])
                    k += 1
                    i += 1
                if i < board_size and i - j < board_size:
                    print(f"tab[{i + 1}][{i - j}] {tab[i][i - j]}")
                    if tab[i][i - j] == 0:
                        open += 1
                print(f"k {k} open {open}")
                result += reward[open][k]
        else:
            i += 1
    j += 1


   0  1  2  3  4
0  7  0  1  0 -1
1  1 -1  1  0  0
2  1  0  0  1  0
3  1  0  0  0  0
4  0  1  0  0  0

j -4
tab[0][4]    0

j -3
tab[0][3]    1
open 0
tab[0][3]    1
tab[1][4]    1
k 2 open 0

j -2
tab[0][2]    1
open 0
tab[0][2]    1
tab[2][3] 0
k 1 open 1
tab[1][3]    0
tab[2][4]    0

j -1
tab[0][1]    1
open 0
tab[0][1]    1
tab[2][2] 0
k 1 open 1
tab[1][2]    0
tab[2][3]    0
tab[3][4]    0

j 0
tab[0][0]    7
tab[1][1]    -1
tab[2][2]    0
tab[3][3]    0
tab[4][4]    0

j 1
tab[1][0]    0
tab[2][1]    1
tab[1][0] 0
open 1
tab[2][1]    1
tab[3][2]    1
tab[5][3] 0
k 2 open 2
tab[4][3]    0

j 2
tab[2][0]    1
open 0
tab[2][0]    1
tab[4][1] 0
k 1 open 1
tab[3][1]    0
tab[4][2]    0

j 3
tab[3][0]    0
tab[4][1]    0

j 4
tab[4][0]    -1


In [68]:
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[0, 0] = 7
tab[0][2] = 1
tab[4][1] = 1
tab[0][4] = -1
tab[1][0] = -1
tab[1][1] = -1
tab[1][2] = 1
tab[2][3] = 1
tab[1][0] = 1
tab[2][0] = 1
tab[3][0] = 1

print(tab)

tab = np.rot90(tab, k=1)

print(tab)

[[ 7  0  1  0 -1]
 [ 1 -1  1  0  0]
 [ 1  0  0  1  0]
 [ 1  0  0  0  0]
 [ 0  1  0  0  0]]
[[-1  0  0  0  0]
 [ 0  0  1  0  0]
 [ 1  1  0  0  0]
 [ 0 -1  0  0  1]
 [ 7  1  1  1  0]]
