In [4]:
import pandas as pd
import numpy as np
import time
import streamlit as st
import functools

In [7]:
win_len = 5
player = 1
score = {1: 0, -1: 0}
valeurs_possibles = [-1, 0, 1]

In [13]:
board_size = 8
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[2][2] = 1
tab[2][3] = 1
tab[2][4] = 1
# tab[5][1] = -1
print(tab)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
j = 0
result = []
while j < board_size:
    i = 0
    while i < board_size:
        cell_value = tab[i][j]
        if cell_value == player:
            k = 0
            pieces = []
            while k < win_len and i < board_size and tab[i][j] == player:
                k += 1
                i += 1
                print(i, j)
                pieces.append([i, j])
            print(pieces)
            if k > 3:
                result.append(pieces)
        else:
            i += 1
    j += 1

print(result)

KeyboardInterrupt: 