In [1]:
import pandas as pd
import numpy as np
import time
import streamlit as st
import functools

In [2]:
win_len = 5
player = 1
score = {1: 0, -1: 0}
valeurs_possibles = [-1, 0, 1]

In [15]:
board_size = 8
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[1][2] = 1
tab[2][2] = 1
tab[3][2] = 1
tab[3][3] = 1
tab[4][4] = 1
# tab[5][1] = -1
print(tab)

[[0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [28]:
%cd ..
from src.hint import check_alignements
%load_ext autoreload
%autoreload 2

res = check_alignements(board_size, win_len, tab, player)
print(res)

/
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[1]
[1, 1]
[1, 1, [[(2, 0), (3, 0), (4, 0)]]]
[1, 1, [[(2, 0), (3, 0), (4, 0)]], []]
[1, 1, [[(2, 0), (3, 0), (4, 0)]], []]
