In [1]:
import pandas as pd
import numpy as np
import time
import streamlit as st
import functools

In [2]:
win_len = 5
player = 1
score = {1: 0, -1: 0}
valeurs_possibles = [-1, 0, 1]

In [3]:
board_size = 8
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[1][2] = 1
tab[2][2] = 1
tab[2][3] = 1
tab[2][4] = 1
tab[3][2] = 1
tab[5][1] = -1
tab[5][3] = 1
tab[6][4] = 1
tab[7][5] = 1
tab[3][5] = 1
tab[4][4] = 1
tab[5][3] = 1
print(tab)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  1  1  1  0  0  0]
 [ 0  0  1  0  0  1  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0 -1  0  1  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  1  0  0]]


In [6]:
%cd ..
from src.hint import check_alignements
%load_ext autoreload
%autoreload 2

liste_initiale = check_alignements(board_size, win_len, tab, player)
print(liste_initiale)

c:\Users\alban\Documents
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[(4, 4), (2, 4), (1, 2), (7, 5), (6, 4), (2, 3), (2, 2), (5, 3), (3, 2), (3, 5)]
