In [1]:
import pandas as pd
import numpy as np
import time

In [22]:
board_size = 6
win_length = 5
player = 1
directions = [(-1, -1),
              (-1, 0),
              (-1, 1),
              (0, -1),
              (0, 1),
              (1, -1),
              (1, 0),
              (1, 1)
              ]

In [49]:
row = 1
col = 1
player = -1
print(f"INIT = tab[{row}][{col}] {tab[row][col]}")
for i in range(8):
        r = row  + directions[i][0]
        c = col + directions[i][1]
        if 0 <= r < board_size and 0 <= c < board_size:
                if tab[r][c] == -player:
                        # print(directions[i][0], directions[i][1])
                        # print(f"ADV tab[{r}][{c}] {tab[r][c]}")
                        r = row - directions[i][0]
                        c = col - directions[i][1]
                        if 0 <= r < board_size and 0 <= c < board_size:
                                if tab[r][c] == player:
                                        print(f"MOI FINAL tab[{r}][{c}] {tab[r][c]}")
                                        r = row  - directions[i][0] * 2
                                        c = col - directions[i][1] * 2
                                        if 0 <= r < board_size and 0 <= c < board_size:
                                                if tab[r][c] == -player:
                                                        print('True')
                                                

INIT = tab[1][1] -1
MOI FINAL tab[1][2] -1
True


In [19]:
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[1][0] = 1
tab[3][0] = 1
tab[4][0] = 1
# tab[1][0] = -1
# tab[1][1] = 0
# tab[1][2] = 1
# tab[1][3] = 1
# tab[2][3] = 1
# tab[1][0] = 1
# tab[2][0] = 1
# tab[3][0] = 1

print(tab)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [31]:
def check_column(board_size, win_len, tab, player):
    i = 0
    result = 0
    while i < board_size:
        j = 0
        while j <= board_size - 1:
            print(f"tab[j][i] tab[{j}][{i}] {tab[j][i]}")
            if tab[j][i] == player:
                if j - 1 >= 0:
                    print(f"tab[j - 1][i] tab[{j - 1}][{i}] {tab[j - 1][i]}")
                    if tab[j - 1][i] == 0:
                        k = 0
                        lap = 0
                        while k < win_len and j < board_size and tab[j][i] != -player and lap < 2:
                            print(f"k {k} lap {lap} j {j} tab[j][i] tab[{j}][{i}]  {tab[j][i]}")
                            if tab[j][i] == player:
                                k += 1
                            else:
                                lap += 1
                            j += 1
                        if j < board_size:
                            if tab[j][i] == 0 and k == 3:
                                result += 1
                    else:
                        j += 1
                else:
                    j += 1
            else:
                j += 1
        i += 1
    return result

In [32]:
res = check_column(len(tab), 3, tab, player)
print(f"res {res}")

tab[j][i] tab[0][0] 0
tab[j][i] tab[1][0] 1
tab[j - 1][i] tab[0][0] 0
k 0 lap 0 j 1 tab[j][i] tab[1][0]  1
k 1 lap 0 j 2 tab[j][i] tab[2][0]  0
k 1 lap 1 j 3 tab[j][i] tab[3][0]  1
k 2 lap 1 j 4 tab[j][i] tab[4][0]  1
tab[j][i] tab[5][0] 0
tab[j][i] tab[0][1] 0
tab[j][i] tab[1][1] 0
tab[j][i] tab[2][1] 0
tab[j][i] tab[3][1] 0
tab[j][i] tab[4][1] 0
tab[j][i] tab[5][1] 0
tab[j][i] tab[0][2] 0
tab[j][i] tab[1][2] 0
tab[j][i] tab[2][2] 0
tab[j][i] tab[3][2] 0
tab[j][i] tab[4][2] 0
tab[j][i] tab[5][2] 0
tab[j][i] tab[0][3] 0
tab[j][i] tab[1][3] 0
tab[j][i] tab[2][3] 0
tab[j][i] tab[3][3] 0
tab[j][i] tab[4][3] 0
tab[j][i] tab[5][3] 0
tab[j][i] tab[0][4] 0
tab[j][i] tab[1][4] 0
tab[j][i] tab[2][4] 0
tab[j][i] tab[3][4] 0
tab[j][i] tab[4][4] 0
tab[j][i] tab[5][4] 0
tab[j][i] tab[0][5] 0
tab[j][i] tab[1][5] 0
tab[j][i] tab[2][5] 0
tab[j][i] tab[3][5] 0
tab[j][i] tab[4][5] 0
tab[j][i] tab[5][5] 0
res 1
