In [2]:
import pandas as pd
import numpy as np
import time

In [17]:
board_size = 5
win_length = 5
player = 1
directions = [(-1, -1),
              (-1, 0),
              (-1, 1),
              (0, -1),
              (0, 1),
              (1, -1),
              (1, 0),
              (1, 1)
              ]

In [34]:
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

tab[0, 0] = 1
tab[0][2] = 1
tab[4][1] = 1
tab[0][4] = -1
tab[1][0] = -1
tab[1][1] = -1
tab[1][2] = -1
tab[1][3] = 1
tab[2][3] = 1
tab[1][0] = 1
tab[2][0] = 1
tab[3][0] = 1

print(tab)

[[ 1  0  1  0 -1]
 [ 1 -1 -1  1  0]
 [ 1  0  0  1  0]
 [ 1  0  0  0  0]
 [ 0  1  0  0  0]]


In [49]:
row = 1
col = 1
player = -1
print(f"INIT = tab[{row}][{col}] {tab[row][col]}")
for i in range(8):
        r = row  + directions[i][0]
        c = col + directions[i][1]
        if 0 <= r < board_size and 0 <= c < board_size:
                if tab[r][c] == -player:
                        # print(directions[i][0], directions[i][1])
                        # print(f"ADV tab[{r}][{c}] {tab[r][c]}")
                        r = row - directions[i][0]
                        c = col - directions[i][1]
                        if 0 <= r < board_size and 0 <= c < board_size:
                                if tab[r][c] == player:
                                        print(f"MOI FINAL tab[{r}][{c}] {tab[r][c]}")
                                        r = row  - directions[i][0] * 2
                                        c = col - directions[i][1] * 2
                                        if 0 <= r < board_size and 0 <= c < board_size:
                                                if tab[r][c] == -player:
                                                        print('True')
                                                

INIT = tab[1][1] -1
MOI FINAL tab[1][2] -1
True
