In [51]:
import pandas as pd
import numpy as np
import time
import re

In [61]:
board_size = 6
win_length = 5
player = 1
directions = [(0, 1),
            (1, 0),
            (1, 1),
            (-1, 1)
            ]

In [68]:
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

row = 3
col = 3

tab[1][0] = 1
tab[3][0] = -1
tab[4][0] = 1
tab[1][1] = 0
tab[1][2] = 1
tab[1][3] = -1
tab[2][3] = 1
tab[2][0] = 1
tab[3][0] = 1
tab[2][2] = 1
tab[2][3] = -1
tab[2][4] = -1
tab[2][5] = 1

print(tab)

[[ 0  0  0  0  0  0]
 [ 1  0  1 -1  0  0]
 [ 1  0  1 -1 -1  1]
 [ 1  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [43]:
row = 2
col = 2
i = 0
lignes = []
for i in range(4):
    ligne = ''  
    # print("IIII", i)
    # print(f"direction {directions[i][0]} / {directions[i][1]}")
    for j in range(-4, 5):
        r = row + j * directions[i][0]
        c = col + j * directions[i][1]
        # print(f"j {j} r {r} c {c} direction {directions[i][0]} / {directions[i][1]}")
        if 0 <= r < board_size and 0 <= c < board_size:
            # print(f"tab[r][c] {tab[r][c]}")
            if tab[r][c] == 0:
                ligne += '_'
            elif tab[r][c] == player:
                ligne += 'X'
            else:
                ligne += 'O'
    # print(ligne)
    lignes.append(ligne)
print(lignes)

['X_OX__', '_XO___', '__O___', 'X_OO_']


In [62]:
def getlines(board_size, win_len, tab, player, row, col):
    lignes = []
    for i in range(win_len - 1):
        ligne = ''  
        for j in range(-(win_len - 1), win_len):
            r = row + j * directions[i][0]
            c = col + j * directions[i][1]
            if 0 <= r < board_size and 0 <= c < board_size:
                if tab[r][c] == 0:
                    ligne += '_'
                elif tab[r][c] == player:
                    ligne += 'X'
                else:
                    ligne += 'O'
        lignes.append(ligne)
    return lignes

def extract_motifs(ligne):
    res = 0
    pattern_scores = [
        ('XXXXX', 100000),   # 5
        ('_XXXX', 10000),    # 4 opened
        ('XXXX_', 10000),    # 4 opened
        ('XXXX', 5000),      # 4 blocked
        ('_XXX', 1000),    # 3 opened
        ('XXX_', 1000),    # 3 opened
        ('XXX', 100),      # 3 blocked
        ('XX', 50),      # 3 blocked
        ('X', 10),      # 3 blocked
    ]
    for pattern, score in pattern_scores:
        index = 0
        while index < len(ligne):
            if ligne[index:].startswith(pattern):
                res += score
                index += 1
            else:
                index += 1
    return res

In [66]:
row = 2
col = 2
lignes = getlines(board_size, 5, tab, player, row, col)
res = 0
print(lignes)
for ligne in lignes:
    res += extract_motifs(ligne)
print(res)

['X_YOOX', '_XY___', '__Y___', 'X_YO_']
0


In [77]:
def getlines(board_size, win_len, tab, player, row, col):
    lignes = []
    for i in range(win_len - 1):
        ligne = ''  
        for j in range(-(win_len - 1), win_len):
            r = row + j * directions[i][0]
            c = col + j * directions[i][1]
            if 0 <= r < board_size and 0 <= c < board_size:
                if r == row and c == col:
                    ligne += 'Y'
                elif tab[r][c] == 0:
                    ligne += '_'
                elif tab[r][c] == player:
                    ligne += 'X'
                else:
                    ligne += 'O'
        lignes.append(ligne)
    return lignes

def extract_motifs(ligne):
    res = 0
    pattern_scores = [
        ('XOOY', 100000),   # capture
        ('YOOX', 100000)   # capture
    ]
    for pattern, score in pattern_scores:
        match = re.search(pattern, ligne)
        print(f"Pattern {pattern} ligne {ligne} match {match}")
        if match:
            res += score
    return res

In [70]:
tab  = [[0 for _ in range(board_size)] for _ in range(board_size)]
tab = np.array(tab)

row = 3
col = 3

tab[1][0] = 1
tab[3][0] = -1
tab[4][0] = 1
tab[1][1] = 0
tab[1][2] = 1
tab[1][3] = -1
tab[2][3] = 1
tab[2][0] = 1
tab[3][0] = 1
tab[2][2] = 1
tab[2][3] = -1
tab[2][4] = -1
tab[2][5] = 1

print(tab)

[[ 0  0  0  0  0  0]
 [ 1  0  1 -1  0  0]
 [ 1  0  1 -1 -1  1]
 [ 1  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [78]:
row = 2
col = 2
lignes = getlines(board_size, 5, tab, player, row, col)
print(lignes)
res = 0
for ligne in lignes:
    res += extract_motifs(ligne)
print(res)

['X_YOOX', '_XY___', '__Y___', 'X_YO_']
Pattern XOOY ligne X_YOOX match None
Pattern YOOX ligne X_YOOX match <re.Match object; span=(2, 6), match='YOOX'>
Pattern XOOY ligne _XY___ match None
Pattern YOOX ligne _XY___ match None
Pattern XOOY ligne __Y___ match None
Pattern YOOX ligne __Y___ match None
Pattern XOOY ligne X_YO_ match None
Pattern YOOX ligne X_YO_ match None
100000


In [76]:
pattern = "YOOX"
string = "X_YOOX"
match = re.search(pattern, string)
if match:
    print("Motif trouvé !")
else:
    print("Motif non trouvé")

Motif trouvé !
